# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf31b826edafc12ee2ccfdb533dc19f5287c61b350703f0af511e9c1d72f8f7b10200e4db0bd0e67014bec57486bee8639c586d31c995fa3ff2e876a1bdf4529

test:
  secret_key_base: a19ec90b0a63871304815004ed83ecca19d2eb9f0e8cf3360b4b01ea463b403d11b6c9878c77b4ef1370bf2ebfe7d6913e2269aa214ce88fa74d1e1fb796de2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
